<a href="https://colab.research.google.com/github/Sweta16676/DMDW-Lab/blob/main/Assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/Rachnagit-hub/DMDW-lab2/main/data.csv'
dt1 = pd.read_csv(url)
dt1.head()

age gender  income  spending
0   22      m   12000      5000
1   25      f   32000      2300
2   23      f   22000      4000
3   22      m   26000      3500

In [2]:
import numpy

In [3]:
arr=numpy.array([1,2,3,4,5])


In [8]:
arr

array([1, 2, 3, 4, 5])

In [14]:
array([1, 2, 3, 4, 5])


NameError: ignored

In [11]:
import numpy as np

In [12]:
arr=np.array([1,2,3,4,5])

In [13]:
print(arr)

[1 2 3 4 5]
